# Generated by Django 5.1.5 on 2025-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_address_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'مدفوع'), ('partial', 'مدفوع جزئيًا'), ('failed', 'فشل الدفع')], default='paid', max_length=10),
        ),
    ]
